import type { SHIPPING_STAGING_STATUSES } from '@modules/Shipping/Domain/Constants/ShippingConstants';

export type ShipmentPackageStagingStatus = (typeof SHIPPING_STAGING_STATUSES)[number];
export type GoodsIssueTrigger = 'at_loading' | 'at_gate_out';
export type GoodsIssueTriggerStatus = 'Pending' | 'Ready';
export type GoodsIssueStatus = 'Pending' | 'Posted' | 'Failed';

export interface ShipmentPackageStaging {
  id: string;
  stagingCode: string;
  packageId: string;
  packageCode: string;
  outboundOrderId: string;
  warehouseProfileId: string;
  warehouseId: string | null;
  warehouseCode: string | null;
  ownerId: string | null;
  ownerCode: string | null;
  status: ShipmentPackageStagingStatus;
  inventoryStatusCode: string | null;
  shipmentReference: string | null;
  stagingLaneCode: string;
  stagingLocationId: string | null;
  stagingLocationCode: string | null;
  dockDoorId: string | null;
  dockDoorCode: string | null;
  truckReference: string | null;
  vehicleNumber: string | null;
  driverName: string | null;
  carrierId: string | null;
  carrierCode: string | null;
  coreFlowInstanceId: string | null;
  stagedAt: string;
  stagedBy: string | null;
  dockAssignedAt: string | null;
  dockAssignedBy: string | null;
  truckAssignedAt: string | null;
  truckAssignedBy: string | null;
  loadReference: string | null;
  loadedAt: string | null;
  loadedBy: string | null;
  shipmentConfirmedAt: string | null;
  shipmentConfirmedBy: string | null;
  gateOutReference: string | null;
  gateOutAt: string | null;
  gateOutBy: string | null;
  goodsIssueTrigger: GoodsIssueTrigger | null;
  goodsIssueTriggerStatus: GoodsIssueTriggerStatus | null;
  goodsIssueTriggeredAt: string | null;
  goodsIssueTriggeredBy: string | null;
  goodsIssueStatus: GoodsIssueStatus | null;
  goodsIssuePostedAt: string | null;
  goodsIssuePostedBy: string | null;
  goodsIssueInventoryTransactionId: string | null;
  goodsIssueInventoryMovementId: string | null;
  loadingOutboxMessageId: string | null;
  shipmentConfirmOutboxMessageId: string | null;
  gateOutOutboxMessageId: string | null;
  goodsIssueTriggerOutboxMessageId: string | null;
  goodsIssueOutboxMessageId: string | null;
  shipmentClosedOutboxMessageId: string | null;
  shipmentClosedAt: string | null;
  createdAt: string;
  updatedAt: string;
}
