import type {
  ControlExceptionCatalogItem,
  ControlValidationCatalog,
  ValidationRuleCatalogItem,
} from '@modules/ControlValidationCatalog/Domain/Entities/ControlValidationCatalog';

export const VALIDATION_RULE_CATALOG: ReadonlyArray<ValidationRuleCatalogItem> = [
  {
    code: 'RBAC-VAL-01',
    description: 'Hành động phải có permission tương ứng trong scope',
    trigger: 'Mọi giao dịch',
    expectedResult: 'Chặn ở backend, ghi attempt nếu nhạy cảm',
    ownerModule: 'C2',
    controlExceptionCode: 'CTRL-EX-01',
    implementationStatus: 'Implemented',
  },
  {
    code: 'RBAC-VAL-02',
    description: 'Data scope theo owner/warehouse/zone',
    trigger: 'WT-05/WT-08 và profile bật scope',
    expectedResult: 'Chặn xem/thao tác ngoài scope',
    ownerModule: 'C2',
    controlExceptionCode: 'CTRL-EX-02',
    implementationStatus: 'Implemented',
  },
  {
    code: 'RBAC-VAL-03',
    description: 'Segregation: người thực hiện khác người duyệt',
    trigger: 'Mọi approval',
    expectedResult: 'Chặn self-approval',
    ownerModule: 'C2,C6',
    controlExceptionCode: 'CTRL-EX-03',
    implementationStatus: 'Implemented',
  },
  {
    code: 'RBAC-VAL-04',
    description: 'Exception phải gắn reason code hợp lệ',
    trigger: 'Mọi exception/thay đổi quan trọng',
    expectedResult: 'Chặn đóng exception nếu thiếu reason',
    ownerModule: 'C9,C3',
    controlExceptionCode: 'CTRL-EX-04',
    implementationStatus: 'DeferredToC9',
  },
  {
    code: 'RBAC-VAL-05',
    description: 'Evidence bắt buộc nếu reason code yêu cầu',
    trigger: 'Theo cấu hình reason',
    expectedResult: 'Chặn resolve nếu thiếu evidence',
    ownerModule: 'C9,C3',
    controlExceptionCode: 'CTRL-EX-04',
    implementationStatus: 'DeferredToC9',
  },
  {
    code: 'RBAC-VAL-06',
    description: 'Approval theo ngưỡng và cấp duyệt',
    trigger: 'Adjustment/override/disposition theo profile',
    expectedResult: 'Chặn nếu chưa đủ cấp duyệt',
    ownerModule: 'C6',
    controlExceptionCode: null,
    implementationStatus: 'Implemented',
  },
  {
    code: 'RBAC-VAL-07',
    description: 'Compliance hard block không được override',
    trigger: 'WT-02/03/04/08 under R-COM',
    expectedResult: 'Hard block; không override path',
    ownerModule: 'C7,B3',
    controlExceptionCode: 'CTRL-EX-05',
    implementationStatus: 'Implemented',
  },
  {
    code: 'RBAC-VAL-08',
    description: 'Mọi giao dịch quan trọng ghi audit before/after',
    trigger: 'Theo 09.01',
    expectedResult: 'Không commit nếu audit fail',
    ownerModule: 'C4,C5',
    controlExceptionCode: null,
    implementationStatus: 'Implemented',
  },
  {
    code: 'RBAC-VAL-09',
    description: 'Audit log immutable',
    trigger: 'Mọi audit',
    expectedResult: 'Không sửa/xóa; chỉ thêm đính chính',
    ownerModule: 'C4',
    controlExceptionCode: null,
    implementationStatus: 'Implemented',
  },
  {
    code: 'RBAC-VAL-10',
    description: 'Override tạo Override Log có reason/approval',
    trigger: 'Mọi override',
    expectedResult: 'Chặn override nếu thiếu reason/approval',
    ownerModule: 'C7',
    controlExceptionCode: null,
    implementationStatus: 'Implemented',
  },
];

export const CONTROL_EXCEPTION_CATALOG: ReadonlyArray<ControlExceptionCatalogItem> = [
  {
    code: 'CTRL-EX-01',
    scenario: 'User thao tác vượt permission',
    category: 'AuthorizationDenied',
    severity: 'High',
    defaultState: 'Blocked',
    actionAllowed: 'Block',
    reasonRequired: false,
    evidenceRequired: false,
    approvalRequired: false,
    ownerRoles: ['WMS_ADMIN'],
    implementationStatus: 'Implemented',
  },
  {
    code: 'CTRL-EX-02',
    scenario: 'Truy cập dữ liệu ngoài data scope',
    category: 'DataScopeViolation',
    severity: 'High',
    defaultState: 'Blocked',
    actionAllowed: 'Block',
    reasonRequired: false,
    evidenceRequired: false,
    approvalRequired: false,
    ownerRoles: ['WMS_ADMIN'],
    implementationStatus: 'Implemented',
  },
  {
    code: 'CTRL-EX-03',
    scenario: 'Self-approval bị phát hiện',
    category: 'SegregationOfDuties',
    severity: 'High',
    defaultState: 'Blocked',
    actionAllowed: 'RouteToOtherApprover',
    reasonRequired: false,
    evidenceRequired: false,
    approvalRequired: false,
    ownerRoles: ['WAREHOUSE_SUPERVISOR', 'WMS_ADMIN'],
    implementationStatus: 'Implemented',
  },
  {
    code: 'CTRL-EX-04',
    scenario: 'Đóng exception thiếu reason/evidence',
    category: 'ExceptionClosure',
    severity: 'Medium',
    defaultState: 'Blocked',
    actionAllowed: 'Block',
    reasonRequired: true,
    evidenceRequired: true,
    approvalRequired: false,
    ownerRoles: ['EXCEPTION_ACTOR'],
    implementationStatus: 'DeferredToC9',
  },
  {
    code: 'CTRL-EX-05',
    scenario: 'Override compliance hard block',
    category: 'ComplianceOverride',
    severity: 'High',
    defaultState: 'Blocked',
    actionAllowed: 'Block',
    reasonRequired: false,
    evidenceRequired: false,
    approvalRequired: false,
    ownerRoles: ['WAREHOUSE_SUPERVISOR', 'COMPLIANCE'],
    implementationStatus: 'Implemented',
  },
  {
    code: 'CTRL-EX-06',
    scenario: 'Approval quá thời gian',
    category: 'ApprovalTimeout',
    severity: 'Medium',
    defaultState: 'Escalated',
    actionAllowed: 'Escalate',
    reasonRequired: false,
    evidenceRequired: false,
    approvalRequired: false,
    ownerRoles: ['WAREHOUSE_SUPERVISOR', 'WMS_ADMIN'],
    implementationStatus: 'DeferredV1Plus',
  },
  {
    code: 'CTRL-EX-07',
    scenario: 'Tần suất override bất thường',
    category: 'OverrideFrequency',
    severity: 'Medium',
    defaultState: 'Warned',
    actionAllowed: 'Warn',
    reasonRequired: false,
    evidenceRequired: false,
    approvalRequired: false,
    ownerRoles: ['WMS_ADMIN', 'WAREHOUSE_SUPERVISOR'],
    implementationStatus: 'DeferredV1Plus',
  },
  {
    code: 'CTRL-EX-08',
    scenario: 'Đổi cấu hình quyền không versioning',
    category: 'ConfigVersioning',
    severity: 'High',
    defaultState: 'Blocked',
    actionAllowed: 'RequireVersionAudit',
    reasonRequired: false,
    evidenceRequired: false,
    approvalRequired: false,
    ownerRoles: ['WMS_ADMIN'],
    implementationStatus: 'Implemented',
  },
  {
    code: 'CTRL-EX-09',
    scenario: 'Manual data fix khi tích hợp lỗi',
    category: 'ManualDataFix',
    severity: 'High',
    defaultState: 'Detected',
    actionAllowed: 'RequireSpecialApproval',
    reasonRequired: true,
    evidenceRequired: true,
    approvalRequired: true,
    ownerRoles: ['IT_WMS_ADMIN', 'INVENTORY_ACCOUNTANT'],
    implementationStatus: 'DeferredV1Plus',
  },
];

export const CONTROL_VALIDATION_SEED_CATALOG: ControlValidationCatalog = {
  validationRules: [...VALIDATION_RULE_CATALOG],
  controlExceptions: [...CONTROL_EXCEPTION_CATALOG],
};
