const OPERATIONAL_LABELS: Record<string, string> = {
  All: 'Tất cả',
  Draft: 'Nháp',
  Active: 'Đang hoạt động',
  Inactive: 'Ngưng hoạt động',
  Requested: 'Đã yêu cầu',
  Previewed: 'Đã xem trước',
  ReprintRequested: 'Đã yêu cầu in lại',
  Reprinted: 'Đã in lại',
  Failed: 'Thất bại',
  Cancelled: 'Đã hủy',
  Ready: 'Sẵn sàng',
  Posted: 'Đã ghi nhận',
  Package: 'Kiện hàng',
  Item: 'Hàng hóa',
  putaway: 'Cất hàng',
  ready_for_staging: 'Sẵn sàng staging',
  loading: 'Chất hàng',
  CountingLocked: 'Đã khóa kiểm kê',
  Submitted: 'Đã gửi',
  PendingReview: 'Chờ rà soát',
  RecountRequired: 'Cần kiểm đếm lại',
  Accepted: 'Đã chấp nhận',
  AdjustmentPosted: 'Đã ghi nhận điều chỉnh',
  Unlocked: 'Đã mở khóa',
  Planned: 'Đã lập kế hoạch',
  Confirmed: 'Đã xác nhận',
  Receiving: 'Đang tiếp nhận',
  PartiallyReceived: 'Nhận một phần',
  Received: 'Đã nhận',
  Closed: 'Đã đóng',
  NotRecorded: 'Chưa ghi nhận',
  Recorded: 'Đã ghi nhận',
  OverrideAccepted: 'Đã chấp nhận ghi đè',
  Allowed: 'Được phép',
  ApprovalRequired: 'Cần phê duyệt',
  Open: 'Đang mở',
  Discrepancy: 'Sai lệch',
  QuantityVariance: 'Chênh lệch số lượng',
  WrongSku: 'Sai SKU',
  WrongUom: 'Sai đơn vị tính',
  UnresolvedBarcode: 'Mã vạch chưa xử lý',
  DamagedGoods: 'Hàng hư hỏng',
  MissingDocument: 'Thiếu chứng từ',
  Routed: 'Đã định tuyến',
  PendingApproval: 'Chờ phê duyệt',
  Blocked: 'Bị chặn',
  NotApplicable: 'Không áp dụng',
  WithinTolerance: 'Trong dung sai',
  OverTolerancePendingApproval: 'Vượt dung sai, chờ phê duyệt',
  OverToleranceHardBlocked: 'Vượt dung sai, bị chặn cứng',
  NotRequired: 'Không bắt buộc',
  PendingQc: 'Chờ QC',
  InInspection: 'Đang kiểm tra',
  Dispositioned: 'Đã xử lý quyết định',
  Passed: 'Đạt',
  ConditionalPassed: 'Đạt có điều kiện',
  Hold: 'Giữ',
  Release: 'Phát hành',
  Quarantine: 'Cách ly',
  Reject: 'Từ chối',
  Damage: 'Hư hỏng',
  Imported: 'Đã import',
  Validated: 'Đã xác thực',
  Held: 'Đang giữ',
  Rejected: 'Đã từ chối',
  FullOnly: 'Chỉ đủ hàng',
  PartialBackorder: 'Một phần/backorder',
  Allocated: 'Đã phân bổ',
  PartiallyAllocated: 'Phân bổ một phần',
  Backordered: 'Backorder',
  Discrete: 'Rời rạc',
  Batch: 'Theo batch',
  Released: 'Đã phát hành',
  InProgress: 'Đang xử lý',
  Completed: 'Hoàn tất',
  Created: 'Đã tạo',
  Exception: 'Ngoại lệ',
  PackingPending: 'Chờ đóng gói',
  Packed: 'Đã đóng gói',
  ReadyForStaging: 'Sẵn sàng staging',
  CheckingPassed: 'Kiểm tra đạt',
  CheckException: 'Ngoại lệ kiểm tra',
  Pending: 'Đang chờ',
  Mismatch: 'Không khớp',
  Staged: 'Đã staging',
  DockAssigned: 'Đã gán dock',
  TruckAssigned: 'Đã gán xe tải',
  ReadyForLoading: 'Sẵn sàng chất hàng',
  Loaded: 'Đã chất hàng',
  ShipmentConfirmed: 'Đã xác nhận lô giao hàng',
  GateOutRecorded: 'Đã ghi nhận cổng ra',
  Retrying: 'Đang thử lại',
  Dispatched: 'Đã gửi đi',
  DeadLetter: 'Hàng đợi lỗi',
  ManualFixed: 'Đã sửa thủ công',
  Acknowledged: 'Đã xác nhận',
  Ignored: 'Đã bỏ qua',
  Transient: 'Tạm thời',
  Validation: 'Lỗi validation',
  Permanent: 'Vĩnh viễn',
  DuplicateConflict: 'Xung đột trùng lặp',
  RetryExhausted: 'Hết lượt thử lại',
  CompletedWithMismatch: 'Hoàn tất có sai lệch',
  Resolved: 'Đã xử lý',
  Low: 'Thấp',
  Medium: 'Trung bình',
  High: 'Cao',
  Receive: 'Tiếp nhận',
  Qc: 'QC',
  Putaway: 'Cất hàng',
  Pick: 'Lấy hàng',
  Pack: 'Đóng gói',
  Load: 'Chất hàng',
  MinMax: 'Min/max',
  Demand: 'Theo nhu cầu',
  EmergencyShortPick: 'Lấy thiếu khẩn cấp',
  PendingRetry: 'Chờ thử lại',
  Claimed: 'Đã nhận',
  Document: 'Chứng từ',
  Location: 'Vị trí',
  Quantity: 'Số lượng',
  Lpn: 'LPN',
  ManualEntry: 'Nhập thủ công',
  ManualOverrideAccepted: 'Đã chấp nhận ghi đè thủ công',
  ShortPick: 'Lấy thiếu',
  NoStock: 'Không có tồn',
  Damaged: 'Hư hỏng',
  WrongItem: 'Sai hàng',
  Allow: 'Cho phép',
  RequireApproval: 'Cần phê duyệt',
  Disallow: 'Không cho phép',
};

export function vietnameseOperationalLabel(value: string | null | undefined): string {
  if (!value) return 'chưa ghi nhận';
  return OPERATIONAL_LABELS[value] ?? value;
}
