/**
 * Centralised route path registry. Reference these constants instead of
 * hard-coding string paths so refactors stay safe across modules.
 */
export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',

  INVENTORY: {
    ROOT: '/inventory',
    DETAIL: (id = ':id') => `/inventory/${id}`,
  },
  FOUNDATION: {
    ROOT: '/foundation',
    LOCATIONS: '/foundation/locations',
    LOCATION_PROFILES: '/foundation/location-profiles',
    LOCATION_PROFILE_NEW: '/foundation/location-profiles/new',
    LOCATION_PROFILE_DETAIL: (id = ':id') => `/foundation/location-profiles/${id}`,
    LOCATION_PROFILE_EDIT: (id = ':id') => `/foundation/location-profiles/${id}/edit`,
    WAREHOUSE_PROFILES: '/foundation/warehouse-profiles',
    RULE_MATRIX: '/foundation/rule-matrix',
    MASTER_DATA: {
      OWNERS: '/foundation/master-data/owners',
      OWNER_NEW: '/foundation/master-data/owners/new',
      OWNER_DETAIL: (id = ':id') => `/foundation/master-data/owners/${id}`,
      OWNER_EDIT: (id = ':id') => `/foundation/master-data/owners/${id}/edit`,
      UOMS: '/foundation/master-data/uoms',
      UOM_NEW: '/foundation/master-data/uoms/new',
      UOM_DETAIL: (id = ':id') => `/foundation/master-data/uoms/${id}`,
      UOM_EDIT: (id = ':id') => `/foundation/master-data/uoms/${id}/edit`,
      SKUS: '/foundation/master-data/skus',
      SKU_NEW: '/foundation/master-data/skus/new',
      SKU_DETAIL: (id = ':id') => `/foundation/master-data/skus/${id}`,
      SKU_EDIT: (id = ':id') => `/foundation/master-data/skus/${id}/edit`,
      PARTNERS: '/foundation/master-data/partners',
      PARTNER_NEW: '/foundation/master-data/partners/new',
      PARTNER_DETAIL: (id = ':id') => `/foundation/master-data/partners/${id}`,
      PARTNER_EDIT: (id = ':id') => `/foundation/master-data/partners/${id}/edit`,
    },
    ACCESS: {
      ROLES: '/foundation/access/roles',
      USERS: '/foundation/access/users',
    },
    AUDIT: '/foundation/audit',
    EXCEPTIONS: '/foundation/exceptions',
    REASON_CODES: '/foundation/reason-codes',
    REASON_CODE_NEW: '/foundation/reason-codes/new',
    REASON_CODE_DETAIL: (id = ':id') => `/foundation/reason-codes/${id}`,
    REASON_CODE_EDIT: (id = ':id') => `/foundation/reason-codes/${id}/edit`,
    INVENTORY_STATUS: '/foundation/inventory-status',
    INVENTORY_STATUS_DETAIL: (id = ':id') => `/foundation/inventory-status/${id}`,
    INVENTORY_STATUS_EDIT: (id = ':id') => `/foundation/inventory-status/${id}/edit`,
    APPROVALS: '/foundation/approvals',
    OVERRIDES: '/foundation/overrides',
    CONTROL_CATALOG: '/foundation/control-catalog',
  },
  WAREHOUSE: { ROOT: '/warehouse' },
  INBOUND: { ROOT: '/inbound' },
  PUTAWAY: { ROOT: '/putaway' },
  REPLENISHMENT: { ROOT: '/replenishment' },
  OUTBOUND: { ROOT: '/outbound' },
  PICKING: { ROOT: '/picking' },
  PACKING: { ROOT: '/packing' },
  SHIPPING: { ROOT: '/shipping' },
  MOBILE: {
    TASKS: '/mobile/tasks',
  },
  LABELS: {
    ROOT: '/labels',
  },
  STOCK_TRANSFER: { ROOT: '/stock-transfer' },
  STOCK_ADJUSTMENT: { ROOT: '/stock-adjustment' },
  CYCLE_COUNT: { ROOT: '/cycle-count' },
  REPORTS: { ROOT: '/reports' },

  NOT_FOUND: '*',
} as const;
